---
- name: Install unzip package
  ansible.builtin.apt:
    name: unzip
    state: present
    update_cache: yes

- name: Create Minecraft directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ server_dir }}"
    - "{{ server_dir }}/mods"
    - "{{ server_dir }}/config"
    - "{{ server_dir }}/world"
    - "{{ server_dir }}/backups"
    - "{{ server_dir }}/resourcepacks"

- name: Check if fantasy modpack zip already exists
  ansible.builtin.stat:
    path: "{{ server_dir }}/fantasy-mc.zip"
  register: zip_stat

- name: Sync fantasy modpack zip file
  ansible.posix.synchronize:
    src: ../fantasy-mc.zip
    dest: "{{ server_dir }}/fantasy-mc.zip"
    mode: push
    rsync_opts:
      - "--progress"
  when: not zip_stat.stat.exists

- name: Unzip fantasy modpack
  ansible.builtin.unarchive:
    src: "{{ server_dir }}/fantasy-mc.zip"
    dest: "{{ server_dir }}"
    remote_src: yes
    extra_opts:
      - -o

- name: Download Fabric server launcher
  get_url:
    url: "https://meta.fabricmc.net/v2/versions/loader/{{ minecraft_version }}/{{ fabric_loader }}/{{ fabric_launcher }}/server/jar"
    dest: "{{ server_dir }}/fabric-server-mc.{{ minecraft_version }}-loader.{{ fabric_loader }}-launcher.{{ fabric_launcher }}.jar"
    mode: "0755"

- name: Download Fabric API (if enabled)
  get_url:
    url: "{{ fabric_api_url }}"
    dest: "{{ server_dir }}/mods/fabric-api.jar"
    mode: "0644"
  when: install_fabric_api and fabric_api_url is defined

- name: Create server.properties from template
  template:
    src: ../templates/server.properties.j2
    dest: "{{ server_dir }}/server.properties"
    mode: "0644"

- name: Create eula.txt (accepting EULA)
  copy:
    content: "eula=true"
    dest: "{{ server_dir }}/eula.txt"
    mode: "0644"

- name: Create start script
  template:
    src: ../templates/start-server.sh.j2
    dest: "{{ server_dir }}/start-server.sh"
    mode: "0755"

- name: Set up systemd service
  template:
    src: ../templates/minecraft.service.j2
    dest: /etc/systemd/system/minecraft.service
    mode: "0644"

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start Minecraft service
  systemd:
    name: minecraft
    enabled: yes
    state: started

- name: Restart Minecraft service
  systemd:
    name: minecraft
    state: restarted
