- name: Restart wireguard
  ansible.builtin.systemd:
    name: wireguard
    state: restarted
    daemon_reload: true
    enabled: true

- name: Reload systemctl
  ansible.builtin.systemd:
    daemon_reload: true
