- name: Reload systemctl
  ansible.builtin.systemd:
    name: wireguard.service
    enabled: true
    daemon_reload: true
    state: restarted

- name: Restart wireguard
  ansible.builtin.systemd:
    name: wireguard
    state: restarted
    daemon_reload: true
    enabled: true
